### PR TITLE
Compatible with SBT 1.0.2 & Slick 3.2.1

### PR DESCRIPTION
**Pull request by borgoat**
Fixing #11, #12, and #13.

Compatible with newer SBT 1.0.2 and Slick 3.2.1,  
also tested against Scala 2.11.11 and H2 1.4.196

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @giorgioazzinnaro,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by motilio** [comment]
Thanks @giorgioazzinnaro 

Is also working with SBT 1.0.2, Slick 3.2.1 and Postgresql 9.5

**Comment by zafarella** [comment]
can confirm - adopted to Postgres - works as expected.
Consider merging asap

**Comment by ghisvail** [comment]
Definitely worth merging. I don't see the value of an official codegen example if it cannot be tested against the latest version of SBT and Slick. Unless the codegen stuff is deprecated.

Whoever is new to the library would checkout the project, test it and give up without even checking the pending PRs. At least, I got the curiosity to check them and found this thread to keep myself going.

**Comment by devsaik** [comment]
am not sure why this is not merged. @giorgioazzinnaro  did you get a chance to sign License Agreement

**Comment by giorgioazzinnaro** [comment]
> am not sure why this is not merged. @giorgioazzinnaro did you get a chance to sign License Agreement

I'm quite sure I did, but just in case, I now did again

**Comment by grzegorz-bielski** [comment]
This is useful, can somebody merge it? 😄

**Comment by SethTisue** [comment]
(as I've said elsewhere, I know essentially nothing about Slick, but I am now available to merge build/test/infra type stuff)

**Comment by SethTisue** [comment]
can anyone who was interested in this also review #17...?

**Pull request merged**
